name: Golang Proxy Scanning

on:
  workflow_dispatch: # Tombol manual untuk menjalankan workflow
  schedule:
    - cron: '0 */12 * * *' # Jalan otomatis tiap 12 jam (2x sehari)

jobs:
  scan-proxies:
    runs-on: ubuntu-latest
    name: 🔎 Scan Proxy Go

    steps:
    - name: 📂 Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SCAN_TOKEN }}

    - name: 🛠️ Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: 🚀 Run Scanner
      run: |
        go run main.go

    - name: 📤 Commit Results
      if: success()
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        git add proxy_health.txt proxy_alive.txt
        git commit -m "🐦‍🔥 Update Proxy: proxy_health.txt & proxy_alive.txt" || echo "No changes to commit"
        git push origin main